### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by mountain-kangkang** [team-dbre/dbre_BE#33]
settings/base.py

```
TIME_ZONE = "Asia/Seoul"
USE_T18N = True
USE_TZ = False
```

docker-compose.yml
```
service:
  db:
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro  # 시간대 정보 추가
    environment:
      - TZ=Asia/Seoul  # 타임존 환경변수 추가
      - PGTZ=Asia/Seoul  # PostgreSQL 전용 타임존 설정

```

현재 상태임
그래도 안되는건 무엇...
